### ISSUE TITLE
Windows/Shared lib/Dll: clib free can't be used on string-results with non shared CRT 

### ISSUE THREAD

**Issue by LowLevelMahn** [kuzudb/kuzu#2527]
all C-API routines that internaly using `convertToOwnedCString` can't be freed on application side using free 
(will crash due to different heaps in application and dll) - under linux sharing is default - on windows its mostly not
thats why most other C libaries like openssl, curl, ... have such "free" functions in their API

crash on free of kuzu_value_get_string result

```
        kuzu_flat_tuple *tuple = kuzu_query_result_get_next(result);

        kuzu_value *value = kuzu_flat_tuple_get_value(tuple, 0);
        char *name = kuzu_value_get_string(value);
        kuzu_value_destroy(value);

        value = kuzu_flat_tuple_get_value(tuple, 1);
        int64_t since = kuzu_value_get_int64(value);
        kuzu_value_destroy(value);

        value = kuzu_flat_tuple_get_value(tuple, 2);
        char *name2 = kuzu_value_get_string(value);
        kuzu_value_destroy(value);

        printf("%s follows %s since %lld \n", name, name2, since);
        free(name); <=== this crashes - due to different Heaps in the kuzu_shared.dll and my application
        free(name2); <=== same crash
        kuzu_flat_tuple_destroy(tuple);
```

these seems to alloc on dll side the string:

- kuzu_flat_tuple_to_string
- kuzu_prepared_statement_get_error_message
- kuzu_query_result_get_column_name
- kuzu_query_result_get_error_message
- kuzu_query_result_to_string
- kuzu_value_get_struct_field_name
- kuzu_int128_t_to_string
- kuzu_value_get_string
- kuzu_value_to_string
- kuzu_node_val_get_property_name_at
- kuzu_node_val_to_string
- kuzu_rel_val_get_property_name_at
- kuzu_rel_val_to_string
- kuzu_value_get_blob

there needs to be something like a kuzu_free(void*) or kuzu_string_free(char*) to make destroying safe

would be also great to have functions that do not allocate but filling a string buffer on the application side

so as alternative to: 

`char *name2 = kuzu_value_get_string(value);`

also

```
int kuzu_value_set_string2(char* buf, max_size);

char name2[30];
res =kuzu_value_set_string2(name2, sizeof(name2));
res == 0, res == -1 (buffer too small)

```

**Comment by acquamarin** [comment]
May i know which compiler are you using on windows?
I don't get a seg fault when freeing the kuzu allocated string using MSVC.

**Comment by LowLevelMahn** [comment]
VS2022 up-to-date, x64, Debug -> using a VS2022 build of Kuzu current git

it would not crash if both Kuzu and the App are sharing the same CRT else it needs to crash

**Comment by zaddach** [comment]
Actually I'd guess that this is related to #3225. You mention explicitly that you build with Debug (using msvcrtd), and Rust on Windows always uses the release version (msvcrt). If you somehow manage to link, you'll still use two different runtimes (debug vs release).

#3226 should fix that..

**Comment by LowLevelMahn** [comment]
its only related if your own application is using a different CRT (debug, release or a complete different compiler version)

if you build the kuzu with a different compiler (using a complete different CRT) it will still not work
but C API means (usualy) "compatible in any case" its not a problem at build time - its a problem at runtime

for a C++ API its common to use the same compiler (what makes it implicitly compatible) but a C API should not depend on using the same compiler - thats the reason for having a C API at all - for not beeing dependent

**Comment by benjaminwinger** [comment]
I believe this has been fixed in #2815 (with more work following that up in #3457, better described in #3133). There is now a `kuzu_destroy_string` function for freeing strings produced by the C API.

https://github.com/kuzudb/kuzu/blob/bc8213e6893e83ee59e6857d912e2a63be551a7d/src/include/c_api/kuzu.h#L1452-L1459

**Comment by mewim** [comment]
> the question is why not kuzu_destroy - anything that gets allocated inside Kuzu dll needs to be freed - not only strings
> 
> > and is preferred over using the standard C free function.
> 
> its not prefered - its needed - or else your using code is dependent on how Kuzu is linked to the project and maybe you're not responsible for that in your project

I think we have now provide a destroy function for everything allocated by kuzu C API (if you search for `destroy` in this file): https://github.com/kuzudb/kuzu/blob/bc8213e6893e83ee59e6857d912e2a63be551a7d/src/include/c_api/kuzu.h

If there is anything still missing, let us know.
